<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZbeCore\Module'                        => __DIR__ . '/Module.php',
    'ZbeCore\Controller\IndexController' => __DIR__ . '/src/ZbeCore/Controller/IndexController.php',
    'ZbeCoreTest\Framework\TestCase'        => __DIR__ . '/tests/ZbeCore/Framework/TestCase.php',
    'ZbeCoreTest\SampleTest'                => __DIR__ . '/tests/ZbeCore/SampleTest.php',
);
