<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZbeAdmin\Module'                        => __DIR__ . '/Module.php',
    'ZbeAdmin\Controller\IndexController' => __DIR__ . '/src/ZbeAdmin/Controller/IndexController.php',
    'ZbeAdminTest\Framework\TestCase'        => __DIR__ . '/tests/ZbeAdmin/Framework/TestCase.php',
    'ZbeAdminTest\SampleTest'                => __DIR__ . '/tests/ZbeAdmin/SampleTest.php',
);
